//! Peripheral event sources for INTC routing on HC32F460.
#![allow(non_upper_case_globals)]

#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(transparent)]
pub struct EventSource(pub u16);

impl EventSource {
    /// INT_SRC_SWI_IRQ0 = 0
    pub const SWI_IRQ0: EventSource = EventSource(0);
    /// INT_SRC_SWI_IRQ1 = 1
    pub const SWI_IRQ1: EventSource = EventSource(1);
    /// INT_SRC_SWI_IRQ2 = 2
    pub const SWI_IRQ2: EventSource = EventSource(2);
    /// INT_SRC_SWI_IRQ3 = 3
    pub const SWI_IRQ3: EventSource = EventSource(3);
    /// INT_SRC_SWI_IRQ4 = 4
    pub const SWI_IRQ4: EventSource = EventSource(4);
    /// INT_SRC_SWI_IRQ5 = 5
    pub const SWI_IRQ5: EventSource = EventSource(5);
    /// INT_SRC_SWI_IRQ6 = 6
    pub const SWI_IRQ6: EventSource = EventSource(6);
    /// INT_SRC_SWI_IRQ7 = 7
    pub const SWI_IRQ7: EventSource = EventSource(7);
    /// INT_SRC_SWI_IRQ8 = 8
    pub const SWI_IRQ8: EventSource = EventSource(8);
    /// INT_SRC_SWI_IRQ9 = 9
    pub const SWI_IRQ9: EventSource = EventSource(9);
    /// INT_SRC_SWI_IRQ10 = 10
    pub const SWI_IRQ10: EventSource = EventSource(10);
    /// INT_SRC_SWI_IRQ11 = 11
    pub const SWI_IRQ11: EventSource = EventSource(11);
    /// INT_SRC_SWI_IRQ12 = 12
    pub const SWI_IRQ12: EventSource = EventSource(12);
    /// INT_SRC_SWI_IRQ13 = 13
    pub const SWI_IRQ13: EventSource = EventSource(13);
    /// INT_SRC_SWI_IRQ14 = 14
    pub const SWI_IRQ14: EventSource = EventSource(14);
    /// INT_SRC_SWI_IRQ15 = 15
    pub const SWI_IRQ15: EventSource = EventSource(15);
    /// INT_SRC_SWI_IRQ16 = 16
    pub const SWI_IRQ16: EventSource = EventSource(16);
    /// INT_SRC_SWI_IRQ17 = 17
    pub const SWI_IRQ17: EventSource = EventSource(17);
    /// INT_SRC_SWI_IRQ18 = 18
    pub const SWI_IRQ18: EventSource = EventSource(18);
    /// INT_SRC_SWI_IRQ19 = 19
    pub const SWI_IRQ19: EventSource = EventSource(19);
    /// INT_SRC_SWI_IRQ20 = 20
    pub const SWI_IRQ20: EventSource = EventSource(20);
    /// INT_SRC_SWI_IRQ21 = 21
    pub const SWI_IRQ21: EventSource = EventSource(21);
    /// INT_SRC_SWI_IRQ22 = 22
    pub const SWI_IRQ22: EventSource = EventSource(22);
    /// INT_SRC_SWI_IRQ23 = 23
    pub const SWI_IRQ23: EventSource = EventSource(23);
    /// INT_SRC_SWI_IRQ24 = 24
    pub const SWI_IRQ24: EventSource = EventSource(24);
    /// INT_SRC_SWI_IRQ25 = 25
    pub const SWI_IRQ25: EventSource = EventSource(25);
    /// INT_SRC_SWI_IRQ26 = 26
    pub const SWI_IRQ26: EventSource = EventSource(26);
    /// INT_SRC_SWI_IRQ27 = 27
    pub const SWI_IRQ27: EventSource = EventSource(27);
    /// INT_SRC_SWI_IRQ28 = 28
    pub const SWI_IRQ28: EventSource = EventSource(28);
    /// INT_SRC_SWI_IRQ29 = 29
    pub const SWI_IRQ29: EventSource = EventSource(29);
    /// INT_SRC_SWI_IRQ30 = 30
    pub const SWI_IRQ30: EventSource = EventSource(30);
    /// INT_SRC_SWI_IRQ31 = 31
    pub const SWI_IRQ31: EventSource = EventSource(31);
    /// INT_SRC_PORT_EIRQ0 = 0
    pub const PORT_EIRQ0: EventSource = EventSource(0);
    /// INT_SRC_PORT_EIRQ1 = 1
    pub const PORT_EIRQ1: EventSource = EventSource(1);
    /// INT_SRC_PORT_EIRQ2 = 2
    pub const PORT_EIRQ2: EventSource = EventSource(2);
    /// INT_SRC_PORT_EIRQ3 = 3
    pub const PORT_EIRQ3: EventSource = EventSource(3);
    /// INT_SRC_PORT_EIRQ4 = 4
    pub const PORT_EIRQ4: EventSource = EventSource(4);
    /// INT_SRC_PORT_EIRQ5 = 5
    pub const PORT_EIRQ5: EventSource = EventSource(5);
    /// INT_SRC_PORT_EIRQ6 = 6
    pub const PORT_EIRQ6: EventSource = EventSource(6);
    /// INT_SRC_PORT_EIRQ7 = 7
    pub const PORT_EIRQ7: EventSource = EventSource(7);
    /// INT_SRC_PORT_EIRQ8 = 8
    pub const PORT_EIRQ8: EventSource = EventSource(8);
    /// INT_SRC_PORT_EIRQ9 = 9
    pub const PORT_EIRQ9: EventSource = EventSource(9);
    /// INT_SRC_PORT_EIRQ10 = 10
    pub const PORT_EIRQ10: EventSource = EventSource(10);
    /// INT_SRC_PORT_EIRQ11 = 11
    pub const PORT_EIRQ11: EventSource = EventSource(11);
    /// INT_SRC_PORT_EIRQ12 = 12
    pub const PORT_EIRQ12: EventSource = EventSource(12);
    /// INT_SRC_PORT_EIRQ13 = 13
    pub const PORT_EIRQ13: EventSource = EventSource(13);
    /// INT_SRC_PORT_EIRQ14 = 14
    pub const PORT_EIRQ14: EventSource = EventSource(14);
    /// INT_SRC_PORT_EIRQ15 = 15
    pub const PORT_EIRQ15: EventSource = EventSource(15);
    /// INT_SRC_DMA1_TC0 = 32
    pub const DMA1_TC0: EventSource = EventSource(32);
    /// INT_SRC_DMA1_TC1 = 33
    pub const DMA1_TC1: EventSource = EventSource(33);
    /// INT_SRC_DMA1_TC2 = 34
    pub const DMA1_TC2: EventSource = EventSource(34);
    /// INT_SRC_DMA1_TC3 = 35
    pub const DMA1_TC3: EventSource = EventSource(35);
    /// INT_SRC_DMA2_TC0 = 36
    pub const DMA2_TC0: EventSource = EventSource(36);
    /// INT_SRC_DMA2_TC1 = 37
    pub const DMA2_TC1: EventSource = EventSource(37);
    /// INT_SRC_DMA2_TC2 = 38
    pub const DMA2_TC2: EventSource = EventSource(38);
    /// INT_SRC_DMA2_TC3 = 39
    pub const DMA2_TC3: EventSource = EventSource(39);
    /// INT_SRC_DMA1_BTC0 = 40
    pub const DMA1_BTC0: EventSource = EventSource(40);
    /// INT_SRC_DMA1_BTC1 = 41
    pub const DMA1_BTC1: EventSource = EventSource(41);
    /// INT_SRC_DMA1_BTC2 = 42
    pub const DMA1_BTC2: EventSource = EventSource(42);
    /// INT_SRC_DMA1_BTC3 = 43
    pub const DMA1_BTC3: EventSource = EventSource(43);
    /// INT_SRC_DMA2_BTC0 = 44
    pub const DMA2_BTC0: EventSource = EventSource(44);
    /// INT_SRC_DMA2_BTC1 = 45
    pub const DMA2_BTC1: EventSource = EventSource(45);
    /// INT_SRC_DMA2_BTC2 = 46
    pub const DMA2_BTC2: EventSource = EventSource(46);
    /// INT_SRC_DMA2_BTC3 = 47
    pub const DMA2_BTC3: EventSource = EventSource(47);
    /// INT_SRC_DMA1_ERR = 48
    pub const DMA1_ERR: EventSource = EventSource(48);
    /// INT_SRC_DMA2_ERR = 49
    pub const DMA2_ERR: EventSource = EventSource(49);
    /// INT_SRC_EFM_PEERR = 50
    pub const EFM_PEERR: EventSource = EventSource(50);
    /// INT_SRC_EFM_COLERR = 51
    pub const EFM_COLERR: EventSource = EventSource(51);
    /// INT_SRC_EFM_OPTEND = 52
    pub const EFM_OPTEND: EventSource = EventSource(52);
    /// INT_SRC_QSPI_INTR = 54
    pub const QSPI_INTR: EventSource = EventSource(54);
    /// INT_SRC_DCU1 = 55
    pub const DCU1: EventSource = EventSource(55);
    /// INT_SRC_DCU2 = 56
    pub const DCU2: EventSource = EventSource(56);
    /// INT_SRC_DCU3 = 57
    pub const DCU3: EventSource = EventSource(57);
    /// INT_SRC_DCU4 = 58
    pub const DCU4: EventSource = EventSource(58);
    /// INT_SRC_TMR0_1_CMP_A = 64
    pub const TMR0_1_CMP_A: EventSource = EventSource(64);
    /// INT_SRC_TMR0_1_CMP_B = 65
    pub const TMR0_1_CMP_B: EventSource = EventSource(65);
    /// INT_SRC_TMR0_2_CMP_A = 66
    pub const TMR0_2_CMP_A: EventSource = EventSource(66);
    /// INT_SRC_TMR0_2_CMP_B = 67
    pub const TMR0_2_CMP_B: EventSource = EventSource(67);
    /// INT_SRC_RTC_ALM = 81
    pub const RTC_ALM: EventSource = EventSource(81);
    /// INT_SRC_RTC_PRD = 82
    pub const RTC_PRD: EventSource = EventSource(82);
    /// INT_SRC_XTAL32_STOP = 84
    pub const XTAL32_STOP: EventSource = EventSource(84);
    /// INT_SRC_XTAL_STOP = 85
    pub const XTAL_STOP: EventSource = EventSource(85);
    /// INT_SRC_WKTM_PRD = 86
    pub const WKTM_PRD: EventSource = EventSource(86);
    /// INT_SRC_SWDT_REFUDF = 87
    pub const SWDT_REFUDF: EventSource = EventSource(87);
    /// INT_SRC_TMR6_1_GCMP_A = 96
    pub const TMR6_1_GCMP_A: EventSource = EventSource(96);
    /// INT_SRC_TMR6_1_GCMP_B = 97
    pub const TMR6_1_GCMP_B: EventSource = EventSource(97);
    /// INT_SRC_TMR6_1_GCMP_C = 98
    pub const TMR6_1_GCMP_C: EventSource = EventSource(98);
    /// INT_SRC_TMR6_1_GCMP_D = 99
    pub const TMR6_1_GCMP_D: EventSource = EventSource(99);
    /// INT_SRC_TMR6_1_GCMP_E = 100
    pub const TMR6_1_GCMP_E: EventSource = EventSource(100);
    /// INT_SRC_TMR6_1_GCMP_F = 101
    pub const TMR6_1_GCMP_F: EventSource = EventSource(101);
    /// INT_SRC_TMR6_1_OVF = 102
    pub const TMR6_1_OVF: EventSource = EventSource(102);
    /// INT_SRC_TMR6_1_UDF = 103
    pub const TMR6_1_UDF: EventSource = EventSource(103);
    /// INT_SRC_TMR6_1_DTE = 104
    pub const TMR6_1_DTE: EventSource = EventSource(104);
    /// INT_SRC_TMR6_1_SCMP_A = 107
    pub const TMR6_1_SCMP_A: EventSource = EventSource(107);
    /// INT_SRC_TMR6_1_SCMP_B = 108
    pub const TMR6_1_SCMP_B: EventSource = EventSource(108);
    /// INT_SRC_TMR6_2_GCMP_A = 112
    pub const TMR6_2_GCMP_A: EventSource = EventSource(112);
    /// INT_SRC_TMR6_2_GCMP_B = 113
    pub const TMR6_2_GCMP_B: EventSource = EventSource(113);
    /// INT_SRC_TMR6_2_GCMP_C = 114
    pub const TMR6_2_GCMP_C: EventSource = EventSource(114);
    /// INT_SRC_TMR6_2_GCMP_D = 115
    pub const TMR6_2_GCMP_D: EventSource = EventSource(115);
    /// INT_SRC_TMR6_2_GCMP_E = 116
    pub const TMR6_2_GCMP_E: EventSource = EventSource(116);
    /// INT_SRC_TMR6_2_GCMP_F = 117
    pub const TMR6_2_GCMP_F: EventSource = EventSource(117);
    /// INT_SRC_TMR6_2_OVF = 118
    pub const TMR6_2_OVF: EventSource = EventSource(118);
    /// INT_SRC_TMR6_2_UDF = 119
    pub const TMR6_2_UDF: EventSource = EventSource(119);
    /// INT_SRC_TMR6_2_DTE = 120
    pub const TMR6_2_DTE: EventSource = EventSource(120);
    /// INT_SRC_TMR6_2_SCMP_A = 123
    pub const TMR6_2_SCMP_A: EventSource = EventSource(123);
    /// INT_SRC_TMR6_2_SCMP_B = 124
    pub const TMR6_2_SCMP_B: EventSource = EventSource(124);
    /// INT_SRC_TMR6_3_GCMP_A = 128
    pub const TMR6_3_GCMP_A: EventSource = EventSource(128);
    /// INT_SRC_TMR6_3_GCMP_B = 129
    pub const TMR6_3_GCMP_B: EventSource = EventSource(129);
    /// INT_SRC_TMR6_3_GCMP_C = 130
    pub const TMR6_3_GCMP_C: EventSource = EventSource(130);
    /// INT_SRC_TMR6_3_GCMP_D = 131
    pub const TMR6_3_GCMP_D: EventSource = EventSource(131);
    /// INT_SRC_TMR6_3_GCMP_E = 132
    pub const TMR6_3_GCMP_E: EventSource = EventSource(132);
    /// INT_SRC_TMR6_3_GCMP_F = 133
    pub const TMR6_3_GCMP_F: EventSource = EventSource(133);
    /// INT_SRC_TMR6_3_OVF = 134
    pub const TMR6_3_OVF: EventSource = EventSource(134);
    /// INT_SRC_TMR6_3_UDF = 135
    pub const TMR6_3_UDF: EventSource = EventSource(135);
    /// INT_SRC_TMR6_3_DTE = 136
    pub const TMR6_3_DTE: EventSource = EventSource(136);
    /// INT_SRC_TMR6_3_SCMP_A = 139
    pub const TMR6_3_SCMP_A: EventSource = EventSource(139);
    /// INT_SRC_TMR6_3_SCMP_B = 140
    pub const TMR6_3_SCMP_B: EventSource = EventSource(140);
    /// INT_SRC_TMRA_1_OVF = 256
    pub const TMRA_1_OVF: EventSource = EventSource(256);
    /// INT_SRC_TMRA_1_UDF = 257
    pub const TMRA_1_UDF: EventSource = EventSource(257);
    /// INT_SRC_TMRA_1_CMP = 258
    pub const TMRA_1_CMP: EventSource = EventSource(258);
    /// INT_SRC_TMRA_2_OVF = 259
    pub const TMRA_2_OVF: EventSource = EventSource(259);
    /// INT_SRC_TMRA_2_UDF = 260
    pub const TMRA_2_UDF: EventSource = EventSource(260);
    /// INT_SRC_TMRA_2_CMP = 261
    pub const TMRA_2_CMP: EventSource = EventSource(261);
    /// INT_SRC_TMRA_3_OVF = 262
    pub const TMRA_3_OVF: EventSource = EventSource(262);
    /// INT_SRC_TMRA_3_UDF = 263
    pub const TMRA_3_UDF: EventSource = EventSource(263);
    /// INT_SRC_TMRA_3_CMP = 264
    pub const TMRA_3_CMP: EventSource = EventSource(264);
    /// INT_SRC_TMRA_4_OVF = 265
    pub const TMRA_4_OVF: EventSource = EventSource(265);
    /// INT_SRC_TMRA_4_UDF = 266
    pub const TMRA_4_UDF: EventSource = EventSource(266);
    /// INT_SRC_TMRA_4_CMP = 267
    pub const TMRA_4_CMP: EventSource = EventSource(267);
    /// INT_SRC_TMRA_5_OVF = 268
    pub const TMRA_5_OVF: EventSource = EventSource(268);
    /// INT_SRC_TMRA_5_UDF = 269
    pub const TMRA_5_UDF: EventSource = EventSource(269);
    /// INT_SRC_TMRA_5_CMP = 270
    pub const TMRA_5_CMP: EventSource = EventSource(270);
    /// INT_SRC_TMRA_6_OVF = 272
    pub const TMRA_6_OVF: EventSource = EventSource(272);
    /// INT_SRC_TMRA_6_UDF = 273
    pub const TMRA_6_UDF: EventSource = EventSource(273);
    /// INT_SRC_TMRA_6_CMP = 274
    pub const TMRA_6_CMP: EventSource = EventSource(274);
    /// INT_SRC_USBFS_GLB = 275
    pub const USBFS_GLB: EventSource = EventSource(275);
    /// INT_SRC_USART1_EI = 278
    pub const USART1_EI: EventSource = EventSource(278);
    /// INT_SRC_USART1_RI = 279
    pub const USART1_RI: EventSource = EventSource(279);
    /// INT_SRC_USART1_TI = 280
    pub const USART1_TI: EventSource = EventSource(280);
    /// INT_SRC_USART1_TCI = 281
    pub const USART1_TCI: EventSource = EventSource(281);
    /// INT_SRC_USART1_RTO = 282
    pub const USART1_RTO: EventSource = EventSource(282);
    /// INT_SRC_USART1_WUPI = 432
    pub const USART1_WUPI: EventSource = EventSource(432);
    /// INT_SRC_USART2_EI = 283
    pub const USART2_EI: EventSource = EventSource(283);
    /// INT_SRC_USART2_RI = 284
    pub const USART2_RI: EventSource = EventSource(284);
    /// INT_SRC_USART2_TI = 285
    pub const USART2_TI: EventSource = EventSource(285);
    /// INT_SRC_USART2_TCI = 286
    pub const USART2_TCI: EventSource = EventSource(286);
    /// INT_SRC_USART2_RTO = 287
    pub const USART2_RTO: EventSource = EventSource(287);
    /// INT_SRC_USART3_EI = 288
    pub const USART3_EI: EventSource = EventSource(288);
    /// INT_SRC_USART3_RI = 289
    pub const USART3_RI: EventSource = EventSource(289);
    /// INT_SRC_USART3_TI = 290
    pub const USART3_TI: EventSource = EventSource(290);
    /// INT_SRC_USART3_TCI = 291
    pub const USART3_TCI: EventSource = EventSource(291);
    /// INT_SRC_USART3_RTO = 292
    pub const USART3_RTO: EventSource = EventSource(292);
    /// INT_SRC_USART4_EI = 293
    pub const USART4_EI: EventSource = EventSource(293);
    /// INT_SRC_USART4_RI = 294
    pub const USART4_RI: EventSource = EventSource(294);
    /// INT_SRC_USART4_TI = 295
    pub const USART4_TI: EventSource = EventSource(295);
    /// INT_SRC_USART4_TCI = 296
    pub const USART4_TCI: EventSource = EventSource(296);
    /// INT_SRC_USART4_RTO = 297
    pub const USART4_RTO: EventSource = EventSource(297);
    /// INT_SRC_SPI1_SPRI = 299
    pub const SPI1_SPRI: EventSource = EventSource(299);
    /// INT_SRC_SPI1_SPTI = 300
    pub const SPI1_SPTI: EventSource = EventSource(300);
    /// INT_SRC_SPI1_SPII = 301
    pub const SPI1_SPII: EventSource = EventSource(301);
    /// INT_SRC_SPI1_SPEI = 302
    pub const SPI1_SPEI: EventSource = EventSource(302);
    /// INT_SRC_SPI2_SPRI = 304
    pub const SPI2_SPRI: EventSource = EventSource(304);
    /// INT_SRC_SPI2_SPTI = 305
    pub const SPI2_SPTI: EventSource = EventSource(305);
    /// INT_SRC_SPI2_SPII = 306
    pub const SPI2_SPII: EventSource = EventSource(306);
    /// INT_SRC_SPI2_SPEI = 307
    pub const SPI2_SPEI: EventSource = EventSource(307);
    /// INT_SRC_SPI3_SPRI = 309
    pub const SPI3_SPRI: EventSource = EventSource(309);
    /// INT_SRC_SPI3_SPTI = 310
    pub const SPI3_SPTI: EventSource = EventSource(310);
    /// INT_SRC_SPI3_SPII = 311
    pub const SPI3_SPII: EventSource = EventSource(311);
    /// INT_SRC_SPI3_SPEI = 312
    pub const SPI3_SPEI: EventSource = EventSource(312);
    /// INT_SRC_SPI4_SPRI = 314
    pub const SPI4_SPRI: EventSource = EventSource(314);
    /// INT_SRC_SPI4_SPTI = 315
    pub const SPI4_SPTI: EventSource = EventSource(315);
    /// INT_SRC_SPI4_SPII = 316
    pub const SPI4_SPII: EventSource = EventSource(316);
    /// INT_SRC_SPI4_SPEI = 317
    pub const SPI4_SPEI: EventSource = EventSource(317);
    /// INT_SRC_TMR4_1_GCMP_UH = 320
    pub const TMR4_1_GCMP_UH: EventSource = EventSource(320);
    /// INT_SRC_TMR4_1_GCMP_UL = 321
    pub const TMR4_1_GCMP_UL: EventSource = EventSource(321);
    /// INT_SRC_TMR4_1_GCMP_VH = 322
    pub const TMR4_1_GCMP_VH: EventSource = EventSource(322);
    /// INT_SRC_TMR4_1_GCMP_VL = 323
    pub const TMR4_1_GCMP_VL: EventSource = EventSource(323);
    /// INT_SRC_TMR4_1_GCMP_WH = 324
    pub const TMR4_1_GCMP_WH: EventSource = EventSource(324);
    /// INT_SRC_TMR4_1_GCMP_WL = 325
    pub const TMR4_1_GCMP_WL: EventSource = EventSource(325);
    /// INT_SRC_TMR4_1_OVF = 326
    pub const TMR4_1_OVF: EventSource = EventSource(326);
    /// INT_SRC_TMR4_1_UDF = 327
    pub const TMR4_1_UDF: EventSource = EventSource(327);
    /// INT_SRC_TMR4_1_RELOAD_U = 328
    pub const TMR4_1_RELOAD_U: EventSource = EventSource(328);
    /// INT_SRC_TMR4_1_RELOAD_V = 329
    pub const TMR4_1_RELOAD_V: EventSource = EventSource(329);
    /// INT_SRC_TMR4_1_RELOAD_W = 330
    pub const TMR4_1_RELOAD_W: EventSource = EventSource(330);
    /// INT_SRC_TMR4_2_GCMP_UH = 336
    pub const TMR4_2_GCMP_UH: EventSource = EventSource(336);
    /// INT_SRC_TMR4_2_GCMP_UL = 337
    pub const TMR4_2_GCMP_UL: EventSource = EventSource(337);
    /// INT_SRC_TMR4_2_GCMP_VH = 338
    pub const TMR4_2_GCMP_VH: EventSource = EventSource(338);
    /// INT_SRC_TMR4_2_GCMP_VL = 339
    pub const TMR4_2_GCMP_VL: EventSource = EventSource(339);
    /// INT_SRC_TMR4_2_GCMP_WH = 340
    pub const TMR4_2_GCMP_WH: EventSource = EventSource(340);
    /// INT_SRC_TMR4_2_GCMP_WL = 341
    pub const TMR4_2_GCMP_WL: EventSource = EventSource(341);
    /// INT_SRC_TMR4_2_OVF = 342
    pub const TMR4_2_OVF: EventSource = EventSource(342);
    /// INT_SRC_TMR4_2_UDF = 343
    pub const TMR4_2_UDF: EventSource = EventSource(343);
    /// INT_SRC_TMR4_2_RELOAD_U = 344
    pub const TMR4_2_RELOAD_U: EventSource = EventSource(344);
    /// INT_SRC_TMR4_2_RELOAD_V = 345
    pub const TMR4_2_RELOAD_V: EventSource = EventSource(345);
    /// INT_SRC_TMR4_2_RELOAD_W = 346
    pub const TMR4_2_RELOAD_W: EventSource = EventSource(346);
    /// INT_SRC_TMR4_3_GCMP_UH = 352
    pub const TMR4_3_GCMP_UH: EventSource = EventSource(352);
    /// INT_SRC_TMR4_3_GCMP_UL = 353
    pub const TMR4_3_GCMP_UL: EventSource = EventSource(353);
    /// INT_SRC_TMR4_3_GCMP_VH = 354
    pub const TMR4_3_GCMP_VH: EventSource = EventSource(354);
    /// INT_SRC_TMR4_3_GCMP_VL = 355
    pub const TMR4_3_GCMP_VL: EventSource = EventSource(355);
    /// INT_SRC_TMR4_3_GCMP_WH = 356
    pub const TMR4_3_GCMP_WH: EventSource = EventSource(356);
    /// INT_SRC_TMR4_3_GCMP_WL = 357
    pub const TMR4_3_GCMP_WL: EventSource = EventSource(357);
    /// INT_SRC_TMR4_3_OVF = 358
    pub const TMR4_3_OVF: EventSource = EventSource(358);
    /// INT_SRC_TMR4_3_UDF = 359
    pub const TMR4_3_UDF: EventSource = EventSource(359);
    /// INT_SRC_TMR4_3_RELOAD_U = 360
    pub const TMR4_3_RELOAD_U: EventSource = EventSource(360);
    /// INT_SRC_TMR4_3_RELOAD_V = 361
    pub const TMR4_3_RELOAD_V: EventSource = EventSource(361);
    /// INT_SRC_TMR4_3_RELOAD_W = 362
    pub const TMR4_3_RELOAD_W: EventSource = EventSource(362);
    /// INT_SRC_EMB_GR0 = 390
    pub const EMB_GR0: EventSource = EventSource(390);
    /// INT_SRC_EMB_GR1 = 391
    pub const EMB_GR1: EventSource = EventSource(391);
    /// INT_SRC_EMB_GR2 = 392
    pub const EMB_GR2: EventSource = EventSource(392);
    /// INT_SRC_EMB_GR3 = 393
    pub const EMB_GR3: EventSource = EventSource(393);
    /// INT_SRC_EVENT_PORT1 = 394
    pub const EVENT_PORT1: EventSource = EventSource(394);
    /// INT_SRC_EVENT_PORT2 = 395
    pub const EVENT_PORT2: EventSource = EventSource(395);
    /// INT_SRC_EVENT_PORT3 = 396
    pub const EVENT_PORT3: EventSource = EventSource(396);
    /// INT_SRC_EVENT_PORT4 = 397
    pub const EVENT_PORT4: EventSource = EventSource(397);
    /// INT_SRC_I2S1_TXIRQOUT = 400
    pub const I2S1_TXIRQOUT: EventSource = EventSource(400);
    /// INT_SRC_I2S1_RXIRQOUT = 401
    pub const I2S1_RXIRQOUT: EventSource = EventSource(401);
    /// INT_SRC_I2S1_ERRIRQOUT = 402
    pub const I2S1_ERRIRQOUT: EventSource = EventSource(402);
    /// INT_SRC_I2S2_TXIRQOUT = 403
    pub const I2S2_TXIRQOUT: EventSource = EventSource(403);
    /// INT_SRC_I2S2_RXIRQOUT = 404
    pub const I2S2_RXIRQOUT: EventSource = EventSource(404);
    /// INT_SRC_I2S2_ERRIRQOUT = 405
    pub const I2S2_ERRIRQOUT: EventSource = EventSource(405);
    /// INT_SRC_I2S3_TXIRQOUT = 406
    pub const I2S3_TXIRQOUT: EventSource = EventSource(406);
    /// INT_SRC_I2S3_RXIRQOUT = 407
    pub const I2S3_RXIRQOUT: EventSource = EventSource(407);
    /// INT_SRC_I2S3_ERRIRQOUT = 408
    pub const I2S3_ERRIRQOUT: EventSource = EventSource(408);
    /// INT_SRC_I2S4_TXIRQOUT = 409
    pub const I2S4_TXIRQOUT: EventSource = EventSource(409);
    /// INT_SRC_I2S4_RXIRQOUT = 410
    pub const I2S4_RXIRQOUT: EventSource = EventSource(410);
    /// INT_SRC_I2S4_ERRIRQOUT = 411
    pub const I2S4_ERRIRQOUT: EventSource = EventSource(411);
    /// INT_SRC_CMP1 = 416
    pub const CMP1: EventSource = EventSource(416);
    /// INT_SRC_CMP2 = 417
    pub const CMP2: EventSource = EventSource(417);
    /// INT_SRC_CMP3 = 418
    pub const CMP3: EventSource = EventSource(418);
    /// INT_SRC_I2C1_RXI = 420
    pub const I2C1_RXI: EventSource = EventSource(420);
    /// INT_SRC_I2C1_TXI = 421
    pub const I2C1_TXI: EventSource = EventSource(421);
    /// INT_SRC_I2C1_TEI = 422
    pub const I2C1_TEI: EventSource = EventSource(422);
    /// INT_SRC_I2C1_EEI = 423
    pub const I2C1_EEI: EventSource = EventSource(423);
    /// INT_SRC_I2C2_RXI = 424
    pub const I2C2_RXI: EventSource = EventSource(424);
    /// INT_SRC_I2C2_TXI = 425
    pub const I2C2_TXI: EventSource = EventSource(425);
    /// INT_SRC_I2C2_TEI = 426
    pub const I2C2_TEI: EventSource = EventSource(426);
    /// INT_SRC_I2C2_EEI = 427
    pub const I2C2_EEI: EventSource = EventSource(427);
    /// INT_SRC_I2C3_RXI = 428
    pub const I2C3_RXI: EventSource = EventSource(428);
    /// INT_SRC_I2C3_TXI = 429
    pub const I2C3_TXI: EventSource = EventSource(429);
    /// INT_SRC_I2C3_TEI = 430
    pub const I2C3_TEI: EventSource = EventSource(430);
    /// INT_SRC_I2C3_EEI = 431
    pub const I2C3_EEI: EventSource = EventSource(431);
    /// INT_SRC_LVD1 = 433
    pub const LVD1: EventSource = EventSource(433);
    /// INT_SRC_LVD2 = 434
    pub const LVD2: EventSource = EventSource(434);
    /// INT_SRC_OTS = 435
    pub const OTS: EventSource = EventSource(435);
    /// INT_SRC_FCMFERRI = 436
    pub const FCMFERRI: EventSource = EventSource(436);
    /// INT_SRC_FCMMENDI = 437
    pub const FCMMENDI: EventSource = EventSource(437);
    /// INT_SRC_FCMCOVFI = 438
    pub const FCMCOVFI: EventSource = EventSource(438);
    /// INT_SRC_WDT_REFUDF = 439
    pub const WDT_REFUDF: EventSource = EventSource(439);
    /// INT_SRC_ADC1_EOCA = 448
    pub const ADC1_EOCA: EventSource = EventSource(448);
    /// INT_SRC_ADC1_EOCB = 449
    pub const ADC1_EOCB: EventSource = EventSource(449);
    /// INT_SRC_ADC1_CHCMP = 450
    pub const ADC1_CHCMP: EventSource = EventSource(450);
    /// INT_SRC_ADC1_SEQCMP = 451
    pub const ADC1_SEQCMP: EventSource = EventSource(451);
    /// INT_SRC_ADC2_EOCA = 452
    pub const ADC2_EOCA: EventSource = EventSource(452);
    /// INT_SRC_ADC2_EOCB = 453
    pub const ADC2_EOCB: EventSource = EventSource(453);
    /// INT_SRC_ADC2_CHCMP = 454
    pub const ADC2_CHCMP: EventSource = EventSource(454);
    /// INT_SRC_ADC2_SEQCMP = 455
    pub const ADC2_SEQCMP: EventSource = EventSource(455);
    /// INT_SRC_TRNG_END = 456
    pub const TRNG_END: EventSource = EventSource(456);
    /// INT_SRC_SDIOC1_SD = 482
    pub const SDIOC1_SD: EventSource = EventSource(482);
    /// INT_SRC_SDIOC2_SD = 485
    pub const SDIOC2_SD: EventSource = EventSource(485);
    /// INT_SRC_CAN_INT = 486
    pub const CAN_INT: EventSource = EventSource(486);
    /// INT_SRC_MAX = 511
    pub const MAX: EventSource = EventSource(511);
}

impl EventSource {
    #[inline]
    pub const fn id(self) -> u16 {
        self.0
    }
}

impl From<u16> for EventSource {
    #[inline]
    fn from(val: u16) -> Self {
        EventSource(val)
    }
}

impl From<EventSource> for u16 {
    #[inline]
    fn from(evt: EventSource) -> Self {
        evt.0
    }
}
