#![allow(warnings)]
#![doc = "Peripheral access API for HC32F460JEUA microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn INT000();
    fn INT001();
    fn INT002();
    fn INT003();
    fn INT004();
    fn INT005();
    fn INT006();
    fn INT007();
    fn INT008();
    fn INT009();
    fn INT010();
    fn INT011();
    fn INT012();
    fn INT013();
    fn INT014();
    fn INT015();
    fn INT016();
    fn INT017();
    fn INT018();
    fn INT019();
    fn INT020();
    fn INT021();
    fn INT022();
    fn INT023();
    fn INT024();
    fn INT025();
    fn INT026();
    fn INT027();
    fn INT028();
    fn INT029();
    fn INT030();
    fn INT031();
    fn INT032();
    fn INT033();
    fn INT034();
    fn INT035();
    fn INT036();
    fn INT037();
    fn INT038();
    fn INT039();
    fn INT040();
    fn INT041();
    fn INT042();
    fn INT043();
    fn INT044();
    fn INT045();
    fn INT046();
    fn INT047();
    fn INT048();
    fn INT049();
    fn INT050();
    fn INT051();
    fn INT052();
    fn INT053();
    fn INT054();
    fn INT055();
    fn INT056();
    fn INT057();
    fn INT058();
    fn INT059();
    fn INT060();
    fn INT061();
    fn INT062();
    fn INT063();
    fn INT064();
    fn INT065();
    fn INT066();
    fn INT067();
    fn INT068();
    fn INT069();
    fn INT070();
    fn INT071();
    fn INT072();
    fn INT073();
    fn INT074();
    fn INT075();
    fn INT076();
    fn INT077();
    fn INT078();
    fn INT079();
    fn INT080();
    fn INT081();
    fn INT082();
    fn INT083();
    fn INT084();
    fn INT085();
    fn INT086();
    fn INT087();
    fn INT088();
    fn INT089();
    fn INT090();
    fn INT091();
    fn INT092();
    fn INT093();
    fn INT094();
    fn INT095();
    fn INT096();
    fn INT097();
    fn INT098();
    fn INT099();
    fn INT100();
    fn INT101();
    fn INT102();
    fn INT103();
    fn INT104();
    fn INT105();
    fn INT106();
    fn INT107();
    fn INT108();
    fn INT109();
    fn INT110();
    fn INT111();
    fn INT112();
    fn INT113();
    fn INT114();
    fn INT115();
    fn INT116();
    fn INT117();
    fn INT118();
    fn INT119();
    fn INT120();
    fn INT121();
    fn INT122();
    fn INT123();
    fn INT124();
    fn INT125();
    fn INT126();
    fn INT127();
    fn INT128();
    fn INT129();
    fn INT130();
    fn INT131();
    fn INT132();
    fn INT133();
    fn INT134();
    fn INT135();
    fn INT136();
    fn INT137();
    fn INT138();
    fn INT139();
    fn INT140();
    fn INT141();
    fn INT142();
    fn INT143();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 144] = [
    Vector { _handler: INT000 },
    Vector { _handler: INT001 },
    Vector { _handler: INT002 },
    Vector { _handler: INT003 },
    Vector { _handler: INT004 },
    Vector { _handler: INT005 },
    Vector { _handler: INT006 },
    Vector { _handler: INT007 },
    Vector { _handler: INT008 },
    Vector { _handler: INT009 },
    Vector { _handler: INT010 },
    Vector { _handler: INT011 },
    Vector { _handler: INT012 },
    Vector { _handler: INT013 },
    Vector { _handler: INT014 },
    Vector { _handler: INT015 },
    Vector { _handler: INT016 },
    Vector { _handler: INT017 },
    Vector { _handler: INT018 },
    Vector { _handler: INT019 },
    Vector { _handler: INT020 },
    Vector { _handler: INT021 },
    Vector { _handler: INT022 },
    Vector { _handler: INT023 },
    Vector { _handler: INT024 },
    Vector { _handler: INT025 },
    Vector { _handler: INT026 },
    Vector { _handler: INT027 },
    Vector { _handler: INT028 },
    Vector { _handler: INT029 },
    Vector { _handler: INT030 },
    Vector { _handler: INT031 },
    Vector { _handler: INT032 },
    Vector { _handler: INT033 },
    Vector { _handler: INT034 },
    Vector { _handler: INT035 },
    Vector { _handler: INT036 },
    Vector { _handler: INT037 },
    Vector { _handler: INT038 },
    Vector { _handler: INT039 },
    Vector { _handler: INT040 },
    Vector { _handler: INT041 },
    Vector { _handler: INT042 },
    Vector { _handler: INT043 },
    Vector { _handler: INT044 },
    Vector { _handler: INT045 },
    Vector { _handler: INT046 },
    Vector { _handler: INT047 },
    Vector { _handler: INT048 },
    Vector { _handler: INT049 },
    Vector { _handler: INT050 },
    Vector { _handler: INT051 },
    Vector { _handler: INT052 },
    Vector { _handler: INT053 },
    Vector { _handler: INT054 },
    Vector { _handler: INT055 },
    Vector { _handler: INT056 },
    Vector { _handler: INT057 },
    Vector { _handler: INT058 },
    Vector { _handler: INT059 },
    Vector { _handler: INT060 },
    Vector { _handler: INT061 },
    Vector { _handler: INT062 },
    Vector { _handler: INT063 },
    Vector { _handler: INT064 },
    Vector { _handler: INT065 },
    Vector { _handler: INT066 },
    Vector { _handler: INT067 },
    Vector { _handler: INT068 },
    Vector { _handler: INT069 },
    Vector { _handler: INT070 },
    Vector { _handler: INT071 },
    Vector { _handler: INT072 },
    Vector { _handler: INT073 },
    Vector { _handler: INT074 },
    Vector { _handler: INT075 },
    Vector { _handler: INT076 },
    Vector { _handler: INT077 },
    Vector { _handler: INT078 },
    Vector { _handler: INT079 },
    Vector { _handler: INT080 },
    Vector { _handler: INT081 },
    Vector { _handler: INT082 },
    Vector { _handler: INT083 },
    Vector { _handler: INT084 },
    Vector { _handler: INT085 },
    Vector { _handler: INT086 },
    Vector { _handler: INT087 },
    Vector { _handler: INT088 },
    Vector { _handler: INT089 },
    Vector { _handler: INT090 },
    Vector { _handler: INT091 },
    Vector { _handler: INT092 },
    Vector { _handler: INT093 },
    Vector { _handler: INT094 },
    Vector { _handler: INT095 },
    Vector { _handler: INT096 },
    Vector { _handler: INT097 },
    Vector { _handler: INT098 },
    Vector { _handler: INT099 },
    Vector { _handler: INT100 },
    Vector { _handler: INT101 },
    Vector { _handler: INT102 },
    Vector { _handler: INT103 },
    Vector { _handler: INT104 },
    Vector { _handler: INT105 },
    Vector { _handler: INT106 },
    Vector { _handler: INT107 },
    Vector { _handler: INT108 },
    Vector { _handler: INT109 },
    Vector { _handler: INT110 },
    Vector { _handler: INT111 },
    Vector { _handler: INT112 },
    Vector { _handler: INT113 },
    Vector { _handler: INT114 },
    Vector { _handler: INT115 },
    Vector { _handler: INT116 },
    Vector { _handler: INT117 },
    Vector { _handler: INT118 },
    Vector { _handler: INT119 },
    Vector { _handler: INT120 },
    Vector { _handler: INT121 },
    Vector { _handler: INT122 },
    Vector { _handler: INT123 },
    Vector { _handler: INT124 },
    Vector { _handler: INT125 },
    Vector { _handler: INT126 },
    Vector { _handler: INT127 },
    Vector { _handler: INT128 },
    Vector { _handler: INT129 },
    Vector { _handler: INT130 },
    Vector { _handler: INT131 },
    Vector { _handler: INT132 },
    Vector { _handler: INT133 },
    Vector { _handler: INT134 },
    Vector { _handler: INT135 },
    Vector { _handler: INT136 },
    Vector { _handler: INT137 },
    Vector { _handler: INT138 },
    Vector { _handler: INT139 },
    Vector { _handler: INT140 },
    Vector { _handler: INT141 },
    Vector { _handler: INT142 },
    Vector { _handler: INT143 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - External interrupt 000 (routed dynamically via INTC matrix)"]
    INT000 = 0,
    #[doc = "1 - External interrupt 001 (routed dynamically via INTC matrix)"]
    INT001 = 1,
    #[doc = "2 - External interrupt 002 (routed dynamically via INTC matrix)"]
    INT002 = 2,
    #[doc = "3 - External interrupt 003 (routed dynamically via INTC matrix)"]
    INT003 = 3,
    #[doc = "4 - External interrupt 004 (routed dynamically via INTC matrix)"]
    INT004 = 4,
    #[doc = "5 - External interrupt 005 (routed dynamically via INTC matrix)"]
    INT005 = 5,
    #[doc = "6 - External interrupt 006 (routed dynamically via INTC matrix)"]
    INT006 = 6,
    #[doc = "7 - External interrupt 007 (routed dynamically via INTC matrix)"]
    INT007 = 7,
    #[doc = "8 - External interrupt 008 (routed dynamically via INTC matrix)"]
    INT008 = 8,
    #[doc = "9 - External interrupt 009 (routed dynamically via INTC matrix)"]
    INT009 = 9,
    #[doc = "10 - External interrupt 010 (routed dynamically via INTC matrix)"]
    INT010 = 10,
    #[doc = "11 - External interrupt 011 (routed dynamically via INTC matrix)"]
    INT011 = 11,
    #[doc = "12 - External interrupt 012 (routed dynamically via INTC matrix)"]
    INT012 = 12,
    #[doc = "13 - External interrupt 013 (routed dynamically via INTC matrix)"]
    INT013 = 13,
    #[doc = "14 - External interrupt 014 (routed dynamically via INTC matrix)"]
    INT014 = 14,
    #[doc = "15 - External interrupt 015 (routed dynamically via INTC matrix)"]
    INT015 = 15,
    #[doc = "16 - External interrupt 016 (routed dynamically via INTC matrix)"]
    INT016 = 16,
    #[doc = "17 - External interrupt 017 (routed dynamically via INTC matrix)"]
    INT017 = 17,
    #[doc = "18 - External interrupt 018 (routed dynamically via INTC matrix)"]
    INT018 = 18,
    #[doc = "19 - External interrupt 019 (routed dynamically via INTC matrix)"]
    INT019 = 19,
    #[doc = "20 - External interrupt 020 (routed dynamically via INTC matrix)"]
    INT020 = 20,
    #[doc = "21 - External interrupt 021 (routed dynamically via INTC matrix)"]
    INT021 = 21,
    #[doc = "22 - External interrupt 022 (routed dynamically via INTC matrix)"]
    INT022 = 22,
    #[doc = "23 - External interrupt 023 (routed dynamically via INTC matrix)"]
    INT023 = 23,
    #[doc = "24 - External interrupt 024 (routed dynamically via INTC matrix)"]
    INT024 = 24,
    #[doc = "25 - External interrupt 025 (routed dynamically via INTC matrix)"]
    INT025 = 25,
    #[doc = "26 - External interrupt 026 (routed dynamically via INTC matrix)"]
    INT026 = 26,
    #[doc = "27 - External interrupt 027 (routed dynamically via INTC matrix)"]
    INT027 = 27,
    #[doc = "28 - External interrupt 028 (routed dynamically via INTC matrix)"]
    INT028 = 28,
    #[doc = "29 - External interrupt 029 (routed dynamically via INTC matrix)"]
    INT029 = 29,
    #[doc = "30 - External interrupt 030 (routed dynamically via INTC matrix)"]
    INT030 = 30,
    #[doc = "31 - External interrupt 031 (routed dynamically via INTC matrix)"]
    INT031 = 31,
    #[doc = "32 - External interrupt 032 (routed dynamically via INTC matrix)"]
    INT032 = 32,
    #[doc = "33 - External interrupt 033 (routed dynamically via INTC matrix)"]
    INT033 = 33,
    #[doc = "34 - External interrupt 034 (routed dynamically via INTC matrix)"]
    INT034 = 34,
    #[doc = "35 - External interrupt 035 (routed dynamically via INTC matrix)"]
    INT035 = 35,
    #[doc = "36 - External interrupt 036 (routed dynamically via INTC matrix)"]
    INT036 = 36,
    #[doc = "37 - External interrupt 037 (routed dynamically via INTC matrix)"]
    INT037 = 37,
    #[doc = "38 - External interrupt 038 (routed dynamically via INTC matrix)"]
    INT038 = 38,
    #[doc = "39 - External interrupt 039 (routed dynamically via INTC matrix)"]
    INT039 = 39,
    #[doc = "40 - External interrupt 040 (routed dynamically via INTC matrix)"]
    INT040 = 40,
    #[doc = "41 - External interrupt 041 (routed dynamically via INTC matrix)"]
    INT041 = 41,
    #[doc = "42 - External interrupt 042 (routed dynamically via INTC matrix)"]
    INT042 = 42,
    #[doc = "43 - External interrupt 043 (routed dynamically via INTC matrix)"]
    INT043 = 43,
    #[doc = "44 - External interrupt 044 (routed dynamically via INTC matrix)"]
    INT044 = 44,
    #[doc = "45 - External interrupt 045 (routed dynamically via INTC matrix)"]
    INT045 = 45,
    #[doc = "46 - External interrupt 046 (routed dynamically via INTC matrix)"]
    INT046 = 46,
    #[doc = "47 - External interrupt 047 (routed dynamically via INTC matrix)"]
    INT047 = 47,
    #[doc = "48 - External interrupt 048 (routed dynamically via INTC matrix)"]
    INT048 = 48,
    #[doc = "49 - External interrupt 049 (routed dynamically via INTC matrix)"]
    INT049 = 49,
    #[doc = "50 - External interrupt 050 (routed dynamically via INTC matrix)"]
    INT050 = 50,
    #[doc = "51 - External interrupt 051 (routed dynamically via INTC matrix)"]
    INT051 = 51,
    #[doc = "52 - External interrupt 052 (routed dynamically via INTC matrix)"]
    INT052 = 52,
    #[doc = "53 - External interrupt 053 (routed dynamically via INTC matrix)"]
    INT053 = 53,
    #[doc = "54 - External interrupt 054 (routed dynamically via INTC matrix)"]
    INT054 = 54,
    #[doc = "55 - External interrupt 055 (routed dynamically via INTC matrix)"]
    INT055 = 55,
    #[doc = "56 - External interrupt 056 (routed dynamically via INTC matrix)"]
    INT056 = 56,
    #[doc = "57 - External interrupt 057 (routed dynamically via INTC matrix)"]
    INT057 = 57,
    #[doc = "58 - External interrupt 058 (routed dynamically via INTC matrix)"]
    INT058 = 58,
    #[doc = "59 - External interrupt 059 (routed dynamically via INTC matrix)"]
    INT059 = 59,
    #[doc = "60 - External interrupt 060 (routed dynamically via INTC matrix)"]
    INT060 = 60,
    #[doc = "61 - External interrupt 061 (routed dynamically via INTC matrix)"]
    INT061 = 61,
    #[doc = "62 - External interrupt 062 (routed dynamically via INTC matrix)"]
    INT062 = 62,
    #[doc = "63 - External interrupt 063 (routed dynamically via INTC matrix)"]
    INT063 = 63,
    #[doc = "64 - External interrupt 064 (routed dynamically via INTC matrix)"]
    INT064 = 64,
    #[doc = "65 - External interrupt 065 (routed dynamically via INTC matrix)"]
    INT065 = 65,
    #[doc = "66 - External interrupt 066 (routed dynamically via INTC matrix)"]
    INT066 = 66,
    #[doc = "67 - External interrupt 067 (routed dynamically via INTC matrix)"]
    INT067 = 67,
    #[doc = "68 - External interrupt 068 (routed dynamically via INTC matrix)"]
    INT068 = 68,
    #[doc = "69 - External interrupt 069 (routed dynamically via INTC matrix)"]
    INT069 = 69,
    #[doc = "70 - External interrupt 070 (routed dynamically via INTC matrix)"]
    INT070 = 70,
    #[doc = "71 - External interrupt 071 (routed dynamically via INTC matrix)"]
    INT071 = 71,
    #[doc = "72 - External interrupt 072 (routed dynamically via INTC matrix)"]
    INT072 = 72,
    #[doc = "73 - External interrupt 073 (routed dynamically via INTC matrix)"]
    INT073 = 73,
    #[doc = "74 - External interrupt 074 (routed dynamically via INTC matrix)"]
    INT074 = 74,
    #[doc = "75 - External interrupt 075 (routed dynamically via INTC matrix)"]
    INT075 = 75,
    #[doc = "76 - External interrupt 076 (routed dynamically via INTC matrix)"]
    INT076 = 76,
    #[doc = "77 - External interrupt 077 (routed dynamically via INTC matrix)"]
    INT077 = 77,
    #[doc = "78 - External interrupt 078 (routed dynamically via INTC matrix)"]
    INT078 = 78,
    #[doc = "79 - External interrupt 079 (routed dynamically via INTC matrix)"]
    INT079 = 79,
    #[doc = "80 - External interrupt 080 (routed dynamically via INTC matrix)"]
    INT080 = 80,
    #[doc = "81 - External interrupt 081 (routed dynamically via INTC matrix)"]
    INT081 = 81,
    #[doc = "82 - External interrupt 082 (routed dynamically via INTC matrix)"]
    INT082 = 82,
    #[doc = "83 - External interrupt 083 (routed dynamically via INTC matrix)"]
    INT083 = 83,
    #[doc = "84 - External interrupt 084 (routed dynamically via INTC matrix)"]
    INT084 = 84,
    #[doc = "85 - External interrupt 085 (routed dynamically via INTC matrix)"]
    INT085 = 85,
    #[doc = "86 - External interrupt 086 (routed dynamically via INTC matrix)"]
    INT086 = 86,
    #[doc = "87 - External interrupt 087 (routed dynamically via INTC matrix)"]
    INT087 = 87,
    #[doc = "88 - External interrupt 088 (routed dynamically via INTC matrix)"]
    INT088 = 88,
    #[doc = "89 - External interrupt 089 (routed dynamically via INTC matrix)"]
    INT089 = 89,
    #[doc = "90 - External interrupt 090 (routed dynamically via INTC matrix)"]
    INT090 = 90,
    #[doc = "91 - External interrupt 091 (routed dynamically via INTC matrix)"]
    INT091 = 91,
    #[doc = "92 - External interrupt 092 (routed dynamically via INTC matrix)"]
    INT092 = 92,
    #[doc = "93 - External interrupt 093 (routed dynamically via INTC matrix)"]
    INT093 = 93,
    #[doc = "94 - External interrupt 094 (routed dynamically via INTC matrix)"]
    INT094 = 94,
    #[doc = "95 - External interrupt 095 (routed dynamically via INTC matrix)"]
    INT095 = 95,
    #[doc = "96 - External interrupt 096 (routed dynamically via INTC matrix)"]
    INT096 = 96,
    #[doc = "97 - External interrupt 097 (routed dynamically via INTC matrix)"]
    INT097 = 97,
    #[doc = "98 - External interrupt 098 (routed dynamically via INTC matrix)"]
    INT098 = 98,
    #[doc = "99 - External interrupt 099 (routed dynamically via INTC matrix)"]
    INT099 = 99,
    #[doc = "100 - External interrupt 100 (routed dynamically via INTC matrix)"]
    INT100 = 100,
    #[doc = "101 - External interrupt 101 (routed dynamically via INTC matrix)"]
    INT101 = 101,
    #[doc = "102 - External interrupt 102 (routed dynamically via INTC matrix)"]
    INT102 = 102,
    #[doc = "103 - External interrupt 103 (routed dynamically via INTC matrix)"]
    INT103 = 103,
    #[doc = "104 - External interrupt 104 (routed dynamically via INTC matrix)"]
    INT104 = 104,
    #[doc = "105 - External interrupt 105 (routed dynamically via INTC matrix)"]
    INT105 = 105,
    #[doc = "106 - External interrupt 106 (routed dynamically via INTC matrix)"]
    INT106 = 106,
    #[doc = "107 - External interrupt 107 (routed dynamically via INTC matrix)"]
    INT107 = 107,
    #[doc = "108 - External interrupt 108 (routed dynamically via INTC matrix)"]
    INT108 = 108,
    #[doc = "109 - External interrupt 109 (routed dynamically via INTC matrix)"]
    INT109 = 109,
    #[doc = "110 - External interrupt 110 (routed dynamically via INTC matrix)"]
    INT110 = 110,
    #[doc = "111 - External interrupt 111 (routed dynamically via INTC matrix)"]
    INT111 = 111,
    #[doc = "112 - External interrupt 112 (routed dynamically via INTC matrix)"]
    INT112 = 112,
    #[doc = "113 - External interrupt 113 (routed dynamically via INTC matrix)"]
    INT113 = 113,
    #[doc = "114 - External interrupt 114 (routed dynamically via INTC matrix)"]
    INT114 = 114,
    #[doc = "115 - External interrupt 115 (routed dynamically via INTC matrix)"]
    INT115 = 115,
    #[doc = "116 - External interrupt 116 (routed dynamically via INTC matrix)"]
    INT116 = 116,
    #[doc = "117 - External interrupt 117 (routed dynamically via INTC matrix)"]
    INT117 = 117,
    #[doc = "118 - External interrupt 118 (routed dynamically via INTC matrix)"]
    INT118 = 118,
    #[doc = "119 - External interrupt 119 (routed dynamically via INTC matrix)"]
    INT119 = 119,
    #[doc = "120 - External interrupt 120 (routed dynamically via INTC matrix)"]
    INT120 = 120,
    #[doc = "121 - External interrupt 121 (routed dynamically via INTC matrix)"]
    INT121 = 121,
    #[doc = "122 - External interrupt 122 (routed dynamically via INTC matrix)"]
    INT122 = 122,
    #[doc = "123 - External interrupt 123 (routed dynamically via INTC matrix)"]
    INT123 = 123,
    #[doc = "124 - External interrupt 124 (routed dynamically via INTC matrix)"]
    INT124 = 124,
    #[doc = "125 - External interrupt 125 (routed dynamically via INTC matrix)"]
    INT125 = 125,
    #[doc = "126 - External interrupt 126 (routed dynamically via INTC matrix)"]
    INT126 = 126,
    #[doc = "127 - External interrupt 127 (routed dynamically via INTC matrix)"]
    INT127 = 127,
    #[doc = "128 - External interrupt 128 (routed dynamically via INTC matrix)"]
    INT128 = 128,
    #[doc = "129 - External interrupt 129 (routed dynamically via INTC matrix)"]
    INT129 = 129,
    #[doc = "130 - External interrupt 130 (routed dynamically via INTC matrix)"]
    INT130 = 130,
    #[doc = "131 - External interrupt 131 (routed dynamically via INTC matrix)"]
    INT131 = 131,
    #[doc = "132 - External interrupt 132 (routed dynamically via INTC matrix)"]
    INT132 = 132,
    #[doc = "133 - External interrupt 133 (routed dynamically via INTC matrix)"]
    INT133 = 133,
    #[doc = "134 - External interrupt 134 (routed dynamically via INTC matrix)"]
    INT134 = 134,
    #[doc = "135 - External interrupt 135 (routed dynamically via INTC matrix)"]
    INT135 = 135,
    #[doc = "136 - External interrupt 136 (routed dynamically via INTC matrix)"]
    INT136 = 136,
    #[doc = "137 - External interrupt 137 (routed dynamically via INTC matrix)"]
    INT137 = 137,
    #[doc = "138 - External interrupt 138 (routed dynamically via INTC matrix)"]
    INT138 = 138,
    #[doc = "139 - External interrupt 139 (routed dynamically via INTC matrix)"]
    INT139 = 139,
    #[doc = "140 - External interrupt 140 (routed dynamically via INTC matrix)"]
    INT140 = 140,
    #[doc = "141 - External interrupt 141 (routed dynamically via INTC matrix)"]
    INT141 = 141,
    #[doc = "142 - External interrupt 142 (routed dynamically via INTC matrix)"]
    INT142 = 142,
    #[doc = "143 - External interrupt 143 (routed dynamically via INTC matrix)"]
    INT143 = 143,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "desc ADC1"]
pub type Adc1 = crate::Periph<adc1::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for Adc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc1").finish()
    }
}
#[doc = "desc ADC1"]
pub mod adc1;
#[doc = "desc ADC2"]
pub type Adc2 = crate::Periph<adc2::RegisterBlock, 0x4004_0400>;
impl core::fmt::Debug for Adc2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc2").finish()
    }
}
#[doc = "desc ADC2"]
pub mod adc2;
#[doc = "desc AES"]
pub type Aes = crate::Periph<aes::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Aes {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aes").finish()
    }
}
#[doc = "desc AES"]
pub mod aes;
#[doc = "desc AOS"]
pub type Aos = crate::Periph<aos::RegisterBlock, 0x4001_0800>;
impl core::fmt::Debug for Aos {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aos").finish()
    }
}
#[doc = "desc AOS"]
pub mod aos;
#[doc = "desc CAN"]
pub type Can = crate::Periph<can::RegisterBlock, 0x4007_0400>;
impl core::fmt::Debug for Can {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Can").finish()
    }
}
#[doc = "desc CAN"]
pub mod can;
#[doc = "desc CMP"]
pub type Cmp1 = crate::Periph<cmp1::RegisterBlock, 0x4004_a000>;
impl core::fmt::Debug for Cmp1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp1").finish()
    }
}
#[doc = "desc CMP"]
pub mod cmp1;
#[doc = "desc CMP"]
pub type Cmp2 = crate::Periph<cmp1::RegisterBlock, 0x4004_a010>;
impl core::fmt::Debug for Cmp2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp2").finish()
    }
}
#[doc = "desc CMP"]
pub use self::cmp1 as cmp2;
#[doc = "desc CMP"]
pub type Cmp3 = crate::Periph<cmp1::RegisterBlock, 0x4004_a020>;
impl core::fmt::Debug for Cmp3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp3").finish()
    }
}
#[doc = "desc CMP"]
pub use self::cmp1 as cmp3;
#[doc = "desc CMPCR"]
pub type Cmpcr = crate::Periph<cmpcr::RegisterBlock, 0x4004_a000>;
impl core::fmt::Debug for Cmpcr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmpcr").finish()
    }
}
#[doc = "desc CMPCR"]
pub mod cmpcr;
#[doc = "desc CMU"]
pub type Cmu = crate::Periph<cmu::RegisterBlock, 0x4005_4000>;
impl core::fmt::Debug for Cmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmu").finish()
    }
}
#[doc = "desc CMU"]
pub mod cmu;
#[doc = "desc CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4000_8c00>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "desc CRC"]
pub mod crc;
#[doc = "desc DBGC"]
pub type Dbgc = crate::Periph<dbgc::RegisterBlock, 0xe004_2000>;
impl core::fmt::Debug for Dbgc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dbgc").finish()
    }
}
#[doc = "desc DBGC"]
pub mod dbgc;
#[doc = "desc DCU"]
pub type Dcu1 = crate::Periph<dcu1::RegisterBlock, 0x4005_2000>;
impl core::fmt::Debug for Dcu1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dcu1").finish()
    }
}
#[doc = "desc DCU"]
pub mod dcu1;
#[doc = "desc DCU"]
pub type Dcu2 = crate::Periph<dcu1::RegisterBlock, 0x4005_2400>;
impl core::fmt::Debug for Dcu2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dcu2").finish()
    }
}
#[doc = "desc DCU"]
pub use self::dcu1 as dcu2;
#[doc = "desc DCU"]
pub type Dcu3 = crate::Periph<dcu1::RegisterBlock, 0x4005_2800>;
impl core::fmt::Debug for Dcu3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dcu3").finish()
    }
}
#[doc = "desc DCU"]
pub use self::dcu1 as dcu3;
#[doc = "desc DCU"]
pub type Dcu4 = crate::Periph<dcu1::RegisterBlock, 0x4005_2c00>;
impl core::fmt::Debug for Dcu4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dcu4").finish()
    }
}
#[doc = "desc DCU"]
pub use self::dcu1 as dcu4;
#[doc = "desc DMA"]
pub type Dma1 = crate::Periph<dma1::RegisterBlock, 0x4005_3000>;
impl core::fmt::Debug for Dma1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma1").finish()
    }
}
#[doc = "desc DMA"]
pub mod dma1;
#[doc = "desc DMA"]
pub type Dma2 = crate::Periph<dma1::RegisterBlock, 0x4005_3400>;
impl core::fmt::Debug for Dma2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma2").finish()
    }
}
#[doc = "desc DMA"]
pub use self::dma1 as dma2;
#[doc = "desc EFM"]
pub type Efm = crate::Periph<efm::RegisterBlock, 0x4001_0400>;
impl core::fmt::Debug for Efm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Efm").finish()
    }
}
#[doc = "desc EFM"]
pub mod efm;
#[doc = "desc EMB"]
pub type Emb0 = crate::Periph<emb0::RegisterBlock, 0x4001_7c00>;
impl core::fmt::Debug for Emb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emb0").finish()
    }
}
#[doc = "desc EMB"]
pub mod emb0;
#[doc = "desc EMB"]
pub type Emb1 = crate::Periph<emb0::RegisterBlock, 0x4001_7c20>;
impl core::fmt::Debug for Emb1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emb1").finish()
    }
}
#[doc = "desc EMB"]
pub use self::emb0 as emb1;
#[doc = "desc EMB"]
pub type Emb2 = crate::Periph<emb0::RegisterBlock, 0x4001_7c40>;
impl core::fmt::Debug for Emb2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emb2").finish()
    }
}
#[doc = "desc EMB"]
pub use self::emb0 as emb2;
#[doc = "desc EMB"]
pub type Emb3 = crate::Periph<emb0::RegisterBlock, 0x4001_7c60>;
impl core::fmt::Debug for Emb3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emb3").finish()
    }
}
#[doc = "desc EMB"]
pub use self::emb0 as emb3;
#[doc = "desc FCM"]
pub type Fcm = crate::Periph<fcm::RegisterBlock, 0x4004_8400>;
impl core::fmt::Debug for Fcm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fcm").finish()
    }
}
#[doc = "desc FCM"]
pub mod fcm;
#[doc = "desc GPIO"]
pub type Gpio = crate::Periph<gpio::RegisterBlock, 0x4005_3800>;
impl core::fmt::Debug for Gpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio").finish()
    }
}
#[doc = "desc GPIO"]
pub mod gpio;
#[doc = "desc HASH"]
pub type Hash = crate::Periph<hash::RegisterBlock, 0x4000_8400>;
impl core::fmt::Debug for Hash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hash").finish()
    }
}
#[doc = "desc HASH"]
pub mod hash;
#[doc = "desc I2C"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x4004_e000>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "desc I2C"]
pub mod i2c1;
#[doc = "desc I2C"]
pub type I2c2 = crate::Periph<i2c1::RegisterBlock, 0x4004_e400>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "desc I2C"]
pub use self::i2c1 as i2c2;
#[doc = "desc I2C"]
pub type I2c3 = crate::Periph<i2c1::RegisterBlock, 0x4004_e800>;
impl core::fmt::Debug for I2c3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c3").finish()
    }
}
#[doc = "desc I2C"]
pub use self::i2c1 as i2c3;
#[doc = "desc I2S"]
pub type I2s1 = crate::Periph<i2s1::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for I2s1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s1").finish()
    }
}
#[doc = "desc I2S"]
pub mod i2s1;
#[doc = "desc I2S"]
pub type I2s2 = crate::Periph<i2s1::RegisterBlock, 0x4001_e400>;
impl core::fmt::Debug for I2s2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s2").finish()
    }
}
#[doc = "desc I2S"]
pub use self::i2s1 as i2s2;
#[doc = "desc I2S"]
pub type I2s3 = crate::Periph<i2s1::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for I2s3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s3").finish()
    }
}
#[doc = "desc I2S"]
pub use self::i2s1 as i2s3;
#[doc = "desc I2S"]
pub type I2s4 = crate::Periph<i2s1::RegisterBlock, 0x4002_2400>;
impl core::fmt::Debug for I2s4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s4").finish()
    }
}
#[doc = "desc I2S"]
pub use self::i2s1 as i2s4;
#[doc = "desc ICG"]
pub type Icg = crate::Periph<icg::RegisterBlock, 0x0400>;
impl core::fmt::Debug for Icg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Icg").finish()
    }
}
#[doc = "desc ICG"]
pub mod icg;
#[doc = "desc INTC"]
pub type Intc = crate::Periph<intc::RegisterBlock, 0x4005_1000>;
impl core::fmt::Debug for Intc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Intc").finish()
    }
}
#[doc = "desc INTC"]
pub mod intc;
#[doc = "desc KEYSCAN"]
pub type Keyscan = crate::Periph<keyscan::RegisterBlock, 0x4005_0c00>;
impl core::fmt::Debug for Keyscan {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Keyscan").finish()
    }
}
#[doc = "desc KEYSCAN"]
pub mod keyscan;
#[doc = "desc OTS"]
pub type Ots = crate::Periph<ots::RegisterBlock, 0x4004_a400>;
impl core::fmt::Debug for Ots {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ots").finish()
    }
}
#[doc = "desc OTS"]
pub mod ots;
#[doc = "desc PERIC"]
pub type Peric = crate::Periph<peric::RegisterBlock, 0x4005_5400>;
impl core::fmt::Debug for Peric {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Peric").finish()
    }
}
#[doc = "desc PERIC"]
pub mod peric;
#[doc = "desc PWC"]
pub type Pwc = crate::Periph<pwc::RegisterBlock, 0x4004_8000>;
impl core::fmt::Debug for Pwc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwc").finish()
    }
}
#[doc = "desc PWC"]
pub mod pwc;
#[doc = "desc QSPI"]
pub type Qspi = crate::Periph<qspi::RegisterBlock, 0x9c00_0000>;
impl core::fmt::Debug for Qspi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qspi").finish()
    }
}
#[doc = "desc QSPI"]
pub mod qspi;
#[doc = "desc RMU"]
pub type Rmu = crate::Periph<rmu::RegisterBlock, 0x4005_40c0>;
impl core::fmt::Debug for Rmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rmu").finish()
    }
}
#[doc = "desc RMU"]
pub mod rmu;
#[doc = "desc RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4004_c000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "desc RTC"]
pub mod rtc;
#[doc = "desc SDIOC"]
pub type Sdioc1 = crate::Periph<sdioc1::RegisterBlock, 0x4006_fc00>;
impl core::fmt::Debug for Sdioc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sdioc1").finish()
    }
}
#[doc = "desc SDIOC"]
pub mod sdioc1;
#[doc = "desc SDIOC"]
pub type Sdioc2 = crate::Periph<sdioc1::RegisterBlock, 0x4007_0000>;
impl core::fmt::Debug for Sdioc2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sdioc2").finish()
    }
}
#[doc = "desc SDIOC"]
pub use self::sdioc1 as sdioc2;
#[doc = "desc SPI"]
pub type Spi1 = crate::Periph<spi1::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "desc SPI"]
pub mod spi1;
#[doc = "desc SPI"]
pub type Spi2 = crate::Periph<spi1::RegisterBlock, 0x4001_c400>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
#[doc = "desc SPI"]
pub use self::spi1 as spi2;
#[doc = "desc SPI"]
pub type Spi3 = crate::Periph<spi1::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
#[doc = "desc SPI"]
pub use self::spi1 as spi3;
#[doc = "desc SPI"]
pub type Spi4 = crate::Periph<spi1::RegisterBlock, 0x4002_0400>;
impl core::fmt::Debug for Spi4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi4").finish()
    }
}
#[doc = "desc SPI"]
pub use self::spi1 as spi4;
#[doc = "desc SRAMC"]
pub type Sramc = crate::Periph<sramc::RegisterBlock, 0x4005_0800>;
impl core::fmt::Debug for Sramc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sramc").finish()
    }
}
#[doc = "desc SRAMC"]
pub mod sramc;
#[doc = "desc SWDT"]
pub type Swdt = crate::Periph<swdt::RegisterBlock, 0x4004_9400>;
impl core::fmt::Debug for Swdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swdt").finish()
    }
}
#[doc = "desc SWDT"]
pub mod swdt;
#[doc = "desc TMR0"]
pub type Tmr01 = crate::Periph<tmr01::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for Tmr01 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr01").finish()
    }
}
#[doc = "desc TMR0"]
pub mod tmr01;
#[doc = "desc TMR0"]
pub type Tmr02 = crate::Periph<tmr01::RegisterBlock, 0x4002_4400>;
impl core::fmt::Debug for Tmr02 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr02").finish()
    }
}
#[doc = "desc TMR0"]
pub use self::tmr01 as tmr02;
#[doc = "desc TMR4"]
pub type Tmr41 = crate::Periph<tmr41::RegisterBlock, 0x4001_7000>;
impl core::fmt::Debug for Tmr41 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr41").finish()
    }
}
#[doc = "desc TMR4"]
pub mod tmr41;
#[doc = "desc TMR4"]
pub type Tmr42 = crate::Periph<tmr41::RegisterBlock, 0x4002_4800>;
impl core::fmt::Debug for Tmr42 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr42").finish()
    }
}
#[doc = "desc TMR4"]
pub use self::tmr41 as tmr42;
#[doc = "desc TMR4"]
pub type Tmr43 = crate::Periph<tmr41::RegisterBlock, 0x4002_4c00>;
impl core::fmt::Debug for Tmr43 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr43").finish()
    }
}
#[doc = "desc TMR4"]
pub use self::tmr41 as tmr43;
#[doc = "desc TMR4CR"]
pub type Tmr4cr = crate::Periph<tmr4cr::RegisterBlock, 0x4005_5408>;
impl core::fmt::Debug for Tmr4cr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr4cr").finish()
    }
}
#[doc = "desc TMR4CR"]
pub mod tmr4cr;
#[doc = "desc TMR6"]
pub type Tmr61 = crate::Periph<tmr61::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Tmr61 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr61").finish()
    }
}
#[doc = "desc TMR6"]
pub mod tmr61;
#[doc = "desc TMR6"]
pub type Tmr62 = crate::Periph<tmr61::RegisterBlock, 0x4001_8400>;
impl core::fmt::Debug for Tmr62 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr62").finish()
    }
}
#[doc = "desc TMR6"]
pub use self::tmr61 as tmr62;
#[doc = "desc TMR6"]
pub type Tmr63 = crate::Periph<tmr61::RegisterBlock, 0x4001_8800>;
impl core::fmt::Debug for Tmr63 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr63").finish()
    }
}
#[doc = "desc TMR6"]
pub use self::tmr61 as tmr63;
#[doc = "desc TMR6CR"]
pub type Tmr6cr = crate::Periph<tmr6cr::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Tmr6cr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr6cr").finish()
    }
}
#[doc = "desc TMR6CR"]
pub mod tmr6cr;
#[doc = "desc TMRA"]
pub type Tmra1 = crate::Periph<tmra1::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for Tmra1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra1").finish()
    }
}
#[doc = "desc TMRA"]
pub mod tmra1;
#[doc = "desc TMRA"]
pub type Tmra2 = crate::Periph<tmra1::RegisterBlock, 0x4001_5400>;
impl core::fmt::Debug for Tmra2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra2").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra2;
#[doc = "desc TMRA"]
pub type Tmra3 = crate::Periph<tmra1::RegisterBlock, 0x4001_5800>;
impl core::fmt::Debug for Tmra3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra3").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra3;
#[doc = "desc TMRA"]
pub type Tmra4 = crate::Periph<tmra1::RegisterBlock, 0x4001_5c00>;
impl core::fmt::Debug for Tmra4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra4").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra4;
#[doc = "desc TMRA"]
pub type Tmra5 = crate::Periph<tmra1::RegisterBlock, 0x4001_6000>;
impl core::fmt::Debug for Tmra5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra5").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra5;
#[doc = "desc TMRA"]
pub type Tmra6 = crate::Periph<tmra1::RegisterBlock, 0x4001_6400>;
impl core::fmt::Debug for Tmra6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra6").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra6;
#[doc = "desc TRNG"]
pub type Trng = crate::Periph<trng::RegisterBlock, 0x4004_1000>;
impl core::fmt::Debug for Trng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trng").finish()
    }
}
#[doc = "desc TRNG"]
pub mod trng;
#[doc = "desc USART"]
pub type Usart1 = crate::Periph<usart1::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Usart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1").finish()
    }
}
#[doc = "desc USART"]
pub mod usart1;
#[doc = "desc USART"]
pub type Usart2 = crate::Periph<usart1::RegisterBlock, 0x4001_d400>;
impl core::fmt::Debug for Usart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart2").finish()
    }
}
#[doc = "desc USART"]
pub use self::usart1 as usart2;
#[doc = "desc USART"]
pub type Usart3 = crate::Periph<usart1::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Usart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart3").finish()
    }
}
#[doc = "desc USART"]
pub use self::usart1 as usart3;
#[doc = "desc USART"]
pub type Usart4 = crate::Periph<usart1::RegisterBlock, 0x4002_1400>;
impl core::fmt::Debug for Usart4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart4").finish()
    }
}
#[doc = "desc USART"]
pub use self::usart1 as usart4;
#[doc = "desc USBFS"]
pub type Usbfs = crate::Periph<usbfs::RegisterBlock, 0x400c_0000>;
impl core::fmt::Debug for Usbfs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbfs").finish()
    }
}
#[doc = "desc USBFS"]
pub mod usbfs;
#[doc = "desc WDT"]
pub type Wdt = crate::Periph<wdt::RegisterBlock, 0x4004_9000>;
impl core::fmt::Debug for Wdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt").finish()
    }
}
#[doc = "desc WDT"]
pub mod wdt;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC1"]
    pub adc1: Adc1,
    #[doc = "ADC2"]
    pub adc2: Adc2,
    #[doc = "AES"]
    pub aes: Aes,
    #[doc = "AOS"]
    pub aos: Aos,
    #[doc = "CAN"]
    pub can: Can,
    #[doc = "CMP1"]
    pub cmp1: Cmp1,
    #[doc = "CMP2"]
    pub cmp2: Cmp2,
    #[doc = "CMP3"]
    pub cmp3: Cmp3,
    #[doc = "CMPCR"]
    pub cmpcr: Cmpcr,
    #[doc = "CMU"]
    pub cmu: Cmu,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "DBGC"]
    pub dbgc: Dbgc,
    #[doc = "DCU1"]
    pub dcu1: Dcu1,
    #[doc = "DCU2"]
    pub dcu2: Dcu2,
    #[doc = "DCU3"]
    pub dcu3: Dcu3,
    #[doc = "DCU4"]
    pub dcu4: Dcu4,
    #[doc = "DMA1"]
    pub dma1: Dma1,
    #[doc = "DMA2"]
    pub dma2: Dma2,
    #[doc = "EFM"]
    pub efm: Efm,
    #[doc = "EMB0"]
    pub emb0: Emb0,
    #[doc = "EMB1"]
    pub emb1: Emb1,
    #[doc = "EMB2"]
    pub emb2: Emb2,
    #[doc = "EMB3"]
    pub emb3: Emb3,
    #[doc = "FCM"]
    pub fcm: Fcm,
    #[doc = "GPIO"]
    pub gpio: Gpio,
    #[doc = "HASH"]
    pub hash: Hash,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "I2C3"]
    pub i2c3: I2c3,
    #[doc = "I2S1"]
    pub i2s1: I2s1,
    #[doc = "I2S2"]
    pub i2s2: I2s2,
    #[doc = "I2S3"]
    pub i2s3: I2s3,
    #[doc = "I2S4"]
    pub i2s4: I2s4,
    #[doc = "ICG"]
    pub icg: Icg,
    #[doc = "INTC"]
    pub intc: Intc,
    #[doc = "KEYSCAN"]
    pub keyscan: Keyscan,
    #[doc = "OTS"]
    pub ots: Ots,
    #[doc = "PERIC"]
    pub peric: Peric,
    #[doc = "PWC"]
    pub pwc: Pwc,
    #[doc = "QSPI"]
    pub qspi: Qspi,
    #[doc = "RMU"]
    pub rmu: Rmu,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SDIOC1"]
    pub sdioc1: Sdioc1,
    #[doc = "SDIOC2"]
    pub sdioc2: Sdioc2,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SPI2"]
    pub spi2: Spi2,
    #[doc = "SPI3"]
    pub spi3: Spi3,
    #[doc = "SPI4"]
    pub spi4: Spi4,
    #[doc = "SRAMC"]
    pub sramc: Sramc,
    #[doc = "SWDT"]
    pub swdt: Swdt,
    #[doc = "TMR01"]
    pub tmr01: Tmr01,
    #[doc = "TMR02"]
    pub tmr02: Tmr02,
    #[doc = "TMR41"]
    pub tmr41: Tmr41,
    #[doc = "TMR42"]
    pub tmr42: Tmr42,
    #[doc = "TMR43"]
    pub tmr43: Tmr43,
    #[doc = "TMR4CR"]
    pub tmr4cr: Tmr4cr,
    #[doc = "TMR61"]
    pub tmr61: Tmr61,
    #[doc = "TMR62"]
    pub tmr62: Tmr62,
    #[doc = "TMR63"]
    pub tmr63: Tmr63,
    #[doc = "TMR6CR"]
    pub tmr6cr: Tmr6cr,
    #[doc = "TMRA1"]
    pub tmra1: Tmra1,
    #[doc = "TMRA2"]
    pub tmra2: Tmra2,
    #[doc = "TMRA3"]
    pub tmra3: Tmra3,
    #[doc = "TMRA4"]
    pub tmra4: Tmra4,
    #[doc = "TMRA5"]
    pub tmra5: Tmra5,
    #[doc = "TMRA6"]
    pub tmra6: Tmra6,
    #[doc = "TRNG"]
    pub trng: Trng,
    #[doc = "USART1"]
    pub usart1: Usart1,
    #[doc = "USART2"]
    pub usart2: Usart2,
    #[doc = "USART3"]
    pub usart3: Usart3,
    #[doc = "USART4"]
    pub usart4: Usart4,
    #[doc = "USBFS"]
    pub usbfs: Usbfs,
    #[doc = "WDT"]
    pub wdt: Wdt,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe { DEVICE_PERIPHERALS = true }
        Peripherals {
            adc1: unsafe { Adc1::steal() },
            adc2: unsafe { Adc2::steal() },
            aes: unsafe { Aes::steal() },
            aos: unsafe { Aos::steal() },
            can: unsafe { Can::steal() },
            cmp1: unsafe { Cmp1::steal() },
            cmp2: unsafe { Cmp2::steal() },
            cmp3: unsafe { Cmp3::steal() },
            cmpcr: unsafe { Cmpcr::steal() },
            cmu: unsafe { Cmu::steal() },
            crc: unsafe { Crc::steal() },
            dbgc: unsafe { Dbgc::steal() },
            dcu1: unsafe { Dcu1::steal() },
            dcu2: unsafe { Dcu2::steal() },
            dcu3: unsafe { Dcu3::steal() },
            dcu4: unsafe { Dcu4::steal() },
            dma1: unsafe { Dma1::steal() },
            dma2: unsafe { Dma2::steal() },
            efm: unsafe { Efm::steal() },
            emb0: unsafe { Emb0::steal() },
            emb1: unsafe { Emb1::steal() },
            emb2: unsafe { Emb2::steal() },
            emb3: unsafe { Emb3::steal() },
            fcm: unsafe { Fcm::steal() },
            gpio: unsafe { Gpio::steal() },
            hash: unsafe { Hash::steal() },
            i2c1: unsafe { I2c1::steal() },
            i2c2: unsafe { I2c2::steal() },
            i2c3: unsafe { I2c3::steal() },
            i2s1: unsafe { I2s1::steal() },
            i2s2: unsafe { I2s2::steal() },
            i2s3: unsafe { I2s3::steal() },
            i2s4: unsafe { I2s4::steal() },
            icg: unsafe { Icg::steal() },
            intc: unsafe { Intc::steal() },
            keyscan: unsafe { Keyscan::steal() },
            ots: unsafe { Ots::steal() },
            peric: unsafe { Peric::steal() },
            pwc: unsafe { Pwc::steal() },
            qspi: unsafe { Qspi::steal() },
            rmu: unsafe { Rmu::steal() },
            rtc: unsafe { Rtc::steal() },
            sdioc1: unsafe { Sdioc1::steal() },
            sdioc2: unsafe { Sdioc2::steal() },
            spi1: unsafe { Spi1::steal() },
            spi2: unsafe { Spi2::steal() },
            spi3: unsafe { Spi3::steal() },
            spi4: unsafe { Spi4::steal() },
            sramc: unsafe { Sramc::steal() },
            swdt: unsafe { Swdt::steal() },
            tmr01: unsafe { Tmr01::steal() },
            tmr02: unsafe { Tmr02::steal() },
            tmr41: unsafe { Tmr41::steal() },
            tmr42: unsafe { Tmr42::steal() },
            tmr43: unsafe { Tmr43::steal() },
            tmr4cr: unsafe { Tmr4cr::steal() },
            tmr61: unsafe { Tmr61::steal() },
            tmr62: unsafe { Tmr62::steal() },
            tmr63: unsafe { Tmr63::steal() },
            tmr6cr: unsafe { Tmr6cr::steal() },
            tmra1: unsafe { Tmra1::steal() },
            tmra2: unsafe { Tmra2::steal() },
            tmra3: unsafe { Tmra3::steal() },
            tmra4: unsafe { Tmra4::steal() },
            tmra5: unsafe { Tmra5::steal() },
            tmra6: unsafe { Tmra6::steal() },
            trng: unsafe { Trng::steal() },
            usart1: unsafe { Usart1::steal() },
            usart2: unsafe { Usart2::steal() },
            usart3: unsafe { Usart3::steal() },
            usart4: unsafe { Usart4::steal() },
            usbfs: unsafe { Usbfs::steal() },
            wdt: unsafe { Wdt::steal() },
        }
    }
}
pub mod events;

#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
